### ISSUE TITLE
Feature: Add Book Details Page

### ISSUE THREAD

**Issue by AKASH-PRASAD7** [AKASH-PRASAD7/Personal-Bookshelf#1]
Issue Title:
Feature Request: Book Page Enhancements

Issue Description:
Feature Request:
Currently, users can search for books, add them to their bookshelf, and remove them. However, I believe that providing more detailed information about each book on a dedicated book page would greatly improve the user experience.

Feature Details:
I propose adding the following enhancements to the book page:

Book Details: Display comprehensive information about the selected book, including its title, author(s), publication date, genre, and a brief summary.

Author Information: Show detailed information about the book's author, such as their name, biography, and a profile image if available.

Reviews: Allow users to read and submit book reviews. Display existing reviews along with user ratings.

Book Cover: Display the book cover image prominently on the page.

Why This Feature is Beneficial:
By providing users with more information about the book, its author, and the opportunity to read and submit reviews, we can create a richer and more engaging experience for our users. This feature will help users make informed decisions about which books to add to their personal bookshelves.

Additional Context:
This feature aligns with our goal to make Personal Bookshelf a comprehensive and user-friendly platform for book enthusiasts. Implementing this enhancement will require fetching and displaying additional data from the Open Library API, as well as creating a user review system.

**Comment by Akshay02022** [comment]
hey  @AKASH-PRASAD7,

That's an intriguing feature that could greatly benefit book enthusiasts by allowing them to choose books tailored to their preferences. I'd like to explore creating a book detail page and give it a try.

**Comment by AKASH-PRASAD7** [comment]
> hey @AKASH-PRASAD7,
> 
> That's an intriguing feature that could greatly benefit book enthusiasts by allowing them to choose books tailored to their preferences. I'd like to explore creating a book detail page and give it a try.

Sure, go for it.

**Comment by Akshay02022** [comment]
I have successfully implemented two features that display the Book Details Page and Author Details Page. However, I'm currently facing some confusion when it comes to implementing the review system. Therefore, for the time being, I have decided to postpone the addition of this feature.
The Book Details Page and Author Details Page Looks like this:
![image](https://github.com/AKASH-PRASAD7/Personal-Bookshelf/assets/98013844/f9f691e8-8175-46b9-8b5a-f33bb0a43a44)
When you click on the image section of the BookCard, it will open the BookDetails Page
![image](https://github.com/AKASH-PRASAD7/Personal-Bookshelf/assets/98013844/7d36f11a-9e09-4af2-899a-64136173927c)
Likewise, when you click on the author's name, it will lead you to the AuthorDetails Page.

Is it advisable for me to submit a pull request for the final code review?

**Comment by AKASH-PRASAD7** [comment]
> I have successfully implemented two features that display the Book Details Page and Author Details Page. However, I'm currently facing some confusion when it comes to implementing the review system. Therefore, for the time being, I have decided to postpone the addition of this feature. The Book Details Page and Author Details Page Looks like this: ![image](https://user-images.githubusercontent.com/98013844/273872266-f9f691e8-8175-46b9-8b5a-f33bb0a43a44.png) When you click on the image section of the BookCard, it will open the BookDetails Page ![image](https://user-images.githubusercontent.com/98013844/273872366-7d36f11a-9e09-4af2-899a-64136173927c.png) Likewise, when you click on the author's name, it will lead you to the AuthorDetails Page.
> 
> Is it advisable for me to submit a pull request for the final code review?

This looks great 👍🏻 and yes you can submit the pull request.
